ADR-971 Only show DSD pages if the appropriate regime is approved
hmrc/alcohol-duty-returns-frontend pull request #102
Opened 2024-06-21 08:23 UTC by davidfes

2024-07-09 09:21 UTC, davidfes commented on app/controllers/TaskListController.scala
> +        Ok(view(taskListViewModel.getTaskList(request.userAnswers, validUntil, periodKey)))
This is now injectable as an object made testing hard

2024-07-09 09:21 UTC, davidfes commented on app/models/TaskListStatus.scala
> +object TaskListStatus extends Enum[TaskListStatus] {
Preferred enums to strings

2024-07-09 09:21 UTC, davidfes commented on app/controllers/TaskListController.scala
> +        Ok(view(taskListViewModel.getTaskList(request.userAnswers, validUntil, periodKey)))
Yash: I agree with making this injectable, thanks for the refactoring. But please move it back to viewmodels. We use service layer to orchestrate calls to backend microservices and for business logic. This class is more about view logic so better keeping it in viewmodels.

2024-07-09 09:21 UTC, davidfes commented on app/controllers/TaskListController.scala
> +        Ok(view(taskListViewModel.getTaskList(request.userAnswers, validUntil, periodKey)))
Done

2024-07-09 09:21 UTC, davidfes commented on app/controllers/actions/CheckRegimeAction.scala
> +      Future.successful(Left(Redirect(controllers.routes.UnauthorisedController.onPageLoad)))
Yash:
As messaged earlier:

Shouldn't return Unauthorised but standard error page for now. We will use Unauthorised page for the cases where the user either needs to create a new GG account or should get an enrolment

2024-07-09 09:21 UTC, davidfes commented on app/controllers/actions/CheckRegimeAction.scala
> +  override protected def refine[A](request: DataRequest[A]): Future[Either[Result, DataRequest[A]]] =
Yash:
As discussed earlier in a call, we are adding regimes: Seq[AlcoholRegime] in the DataRequest in ADR-1028 branch. Let's follow the same approach here

2024-07-09 09:21 UTC, davidfes commented on app/controllers/actions/CheckRegimeAction.scala
> +  override protected def refine[A](request: DataRequest[A]): Future[Either[Result, DataRequest[A]]] =
That's merged now - the only thing that was relevant post-merge was view order - which I noted was defined by values in the enum. This (get the view order for what you have) was refactored and now is on AlcoholRegimes which navigator also uses now.

2024-07-09 09:21 UTC, davidfes commented on app/models/AlcoholRegimes.scala
>    def hasOtherFermentedProduct() = regimes.contains(OtherFermentedProduct)
Yash: As discussed earlier in a call, we are adding regimes: Seq[AlcoholRegime] in the DataRequest in ADR-1028 branch. Let's follow the same approach here

2024-07-09 09:21 UTC, davidfes commented on app/models/AlcoholRegimes.scala
>    def hasOtherFermentedProduct() = regimes.contains(OtherFermentedProduct)
Cider isn't add though which was one of the asks on the ticket to also go to OtherFermented. I agree if that was fixed, but is it safe to do so?

2024-07-09 09:21 UTC, davidfes commented on app/models/AlcoholRegimes.scala
>    def hasOtherFermentedProduct() = regimes.contains(OtherFermentedProduct)
Update this was moved into account on 1132 (the pre-refactor) which due to misunderstandings isn't correct now. However we'd said we'd wait until outcomes of the regime approval discussion before making further changes. The auto-add of OFP from cider can be removed there. And in doing so a couple of the TestData examples here should be modified if changed (e.g. no Cider would now have OFP if not auto added) and maybe a couple of tests might need updating to cover that case.

2024-07-09 09:21 UTC, davidfes commented on app/models/AlcoholRegimes.scala
> +    current.fold(regimesInViewOrder().headOption)(regimesInViewOrder().toList.nextItem(_))
Yash: This looks to me a specific logic for Duty Suspended pages so better move it to DeclareDutySuspendedDeliveriesNavigator

2024-07-09 09:21 UTC, davidfes commented on app/models/AlcoholRegimes.scala
> +    current.fold(regimesInViewOrder().headOption)(regimesInViewOrder().toList.nextItem(_))
Originally it got moved back there, but with regime view order being 'introduced' in 1028, I think this belongs here with the view order of regimes and may have other uses in the future. The navigator now doesn't have to know about view order (which is consistent across the server) as a concern, and avoids a potential duplication later.

2024-07-09 09:21 UTC, davidfes commented on app/models/TaskListStatus.scala
> +  def entryNameLower: String = entryName.toLowerCase
Yash: Instead of calling Lowercase everytime this is used, please add entryName here

2024-07-09 09:21 UTC, davidfes commented on app/models/TaskListStatus.scala
> +  def entryNameLower: String = entryName.toLowerCase
IMO We shouldn't override entryName (since that's expected to return the enum as-is and if not final may have unintended consequences), but created a entryNameLower to cater for the one place we need to use it.

2024-07-09 12:03 UTC, yasaracar requested changes

2024-07-10 08:10 UTC, yasaracar commented on app/models/TaskListStatus.scala
> +  def entryNameLower: String = entryName.toLowerCase
I meant moving the whole TaskListStatus to ViewModels as they apply to views only but anyways we'll refactor later

2024-07-10 08:10 UTC, yasaracar approved these changes

2024-07-10 08:30 UTC, merged