ADR-1077: Adjustments Journey
hmrc/alcohol-duty-returns-frontend pull request #107
Opened 2024-07-11 10:57 UTC by sini-george

2024-07-14 20:53 UTC, davidfes commented on app/connectors/DutyCalculation.scala
> +  implicit val formats: OFormat[AdjustmentDutyCalculationRequest] = Json.format[AdjustmentDutyCalculationRequest]
Would use a better name here. When you turn on show implicits, formats doesn't tell you much, although there is little else it could be given the type.

2024-07-14 20:53 UTC, davidfes commented on app/controllers/adjustment/AdjustmentVolumeWithSPRController.scala
> +      .map(_.rangeDetails.map(_.alcoholRegime).head)
head is an anti-pattern as it throws with an generic exempt. Consider headOptoin and flatMap it to throw a more useful exception if something is wrong

2024-07-14 20:53 UTC, davidfes commented on app/controllers/adjustment/DeleteAdjustmentController.scala
> +    val preparedForm = request.userAnswers.get(DeleteAdjustmentPage) match {
prefer fold

2024-07-14 20:53 UTC, davidfes commented on app/models/adjustment/AdjustmentEntry.scala
> +      case (Some(_), None) => rateBand.map(_.rate).get
even though we know you can get a value, better to avoid the linter wrath and use

case(maybeRate @ Some(rate), None) => maybeRate

Also saves getting it again

2024-07-14 20:53 UTC, davidfes commented on app/models/adjustment/AdjustmentEntry.scala
> +      case (Some(_), None) => repackagedRateBand.map(_.rate).get
as above

2024-07-14 20:53 UTC, davidfes commented on app/models/adjustment/AdjustmentType.scala
> +  def options(implicit messages: Messages): Seq[RadioItem] = values.map { value =>
Wondering if a better name of the method would be clearer here.

2024-07-14 20:53 UTC, davidfes commented on app/navigation/AdjustmentNavigator.scala
>        adjustment <- userAnswers.get(pages.adjustment.CurrentAdjustmentEntryPage)
Seems a little overkill for a for, but I guess that's taste

2024-07-14 20:53 UTC, davidfes commented on test/controllers/adjustment/AdjustmentTaxTypeControllerSpec.scala
> +      val mockAlcoholDutyCalculatorConnector = mock[AlcoholDutyCalculatorConnector]
consider using a fixture (in new SetUp {   class SetUp { mocks and data here) } to group data and mocks (avoiding have to create mocks in each test). Also consider any reusable structures to go in TestData which is included with SpecBase

2024-07-15 11:20 UTC, sini-george commented on app/controllers/adjustment/AdjustmentRepackagedTaxTypeController.scala
> +    adjustmentEntry.repackagedRateBand.map(_.taxTypeCode) match {
Yes In case the value changed it impacts the upcoming screens calculations, else sometimes the CYA screen can have previous values. This is a pattern we created during the old returns journey

2024-07-15 12:33 UTC, sini-george commented on app/connectors/DutyCalculation.scala
> +  implicit val formats: OFormat[AdjustmentDutyCalculationRequest] = Json.format[AdjustmentDutyCalculationRequest]
Had a discussion with Yash earlier on this, and we agreed on the names at that time, these match with what is there in the back end too, can check again with him

2024-07-15 15:51 UTC, sini-george commented on app/controllers/adjustment/AdjustmentListController.scala
> +    val table = AdjustmentListSummaryHelper.adjustmentEntryTable(request.userAnswers, 0)
I think we need to discuss this one, not sure why totals is being taken out, as we still need it

2024-07-15 15:52 UTC, sini-george commented on app/controllers/adjustment/AdjustmentRepackagedTaxTypeController.scala
> +                .getOrElse(throw new RuntimeException("Couldn't fetch taxCode value from cache"))
Yes, I feel like if a repackagedRateBand  is defined(checked prior to this line) the taxTypeCode for it should also exist

2024-07-15 15:57 UTC, sini-george commented on app/controllers/adjustment/AdjustmentTaxTypeController.scala
> +      case Some(existingValue) if currentValue.toString == existingValue => (adjustmentEntry, false)
added comment above

2024-07-15 15:59 UTC, sini-george commented on app/views/ViewUtils.scala
> +    val formattedValue = decimalFormat.format(value.abs)
Sure I can pull the same, once it is merged

2024-07-17 14:40 UTC, sini-george commented on app/views/ViewUtils.scala
> +    val formattedValue = decimalFormat.format(value.abs)
This has been done after the merge

2024-07-17 14:53 UTC, yasaracar commented on app/config/FrontendAppConfig.scala
> +    adrCalculatorHost + adrCalculatorRootUrl + adrCalculatorCalculateAdjustmentDutyUrlPart
The whole file is using +, so a tech debt but not a high priority

2024-07-17 16:06 UTC, sini-george commented on app/viewmodels/checkAnswers/adjustment/AdjustmentListSummaryHelper.scala
> +object AdjustmentListSummaryHelper {
Used object as I referred the existing code, and see that we mostly used objects

2024-07-19 07:45 UTC, sini-george commented on app/controllers/adjustment/AdjustmentListController.scala
> +    val table = AdjustmentListSummaryHelper.adjustmentEntryTable(request.userAnswers, 0)
I checked the tableTotalViewmodel changes and have added them here, also changed the logic to save the total in the cache

2024-07-19 07:46 UTC, sini-george commented on app/controllers/adjustment/AdjustmentRepackagedTaxTypeController.scala
> +                .getOrElse(throw new RuntimeException("Couldn't fetch taxCode value from cache"))
Code has been modified to not throw exceptions

2024-07-19 07:52 UTC, sini-george commented on app/navigation/AdjustmentNavigator.scala
>        adjustment <- userAnswers.get(pages.adjustment.CurrentAdjustmentEntryPage)
this logic has been modified

2024-07-22 15:16 UTC, yasaracar requested changes

2024-07-22 15:16 UTC, yasaracar commented on app/controllers/adjustment/AdjustmentTaxTypeController.scala
> +                  case _                                    => Future.successful(Redirect(controllers.routes.JourneyRecoveryController.onPageLoad()))
Add logger please

2024-07-22 15:16 UTC, yasaracar commented on app/controllers/adjustment/AdjustmentTaxTypeController.scala
> +                Future.successful(Redirect(controllers.routes.JourneyRecoveryController.onPageLoad()))
Add logger please

2024-07-22 15:16 UTC, yasaracar commented on app/controllers/adjustment/AdjustmentTaxTypeController.scala
> +      case _                                                                            => Future.successful(Redirect(controllers.routes.JourneyRecoveryController.onPageLoad()))
Add logger please

2024-07-22 15:16 UTC, yasaracar commented on app/controllers/adjustment/AdjustmentDutyDueController.scala
>      result.getOrElse(Redirect(controllers.routes.JourneyRecoveryController.onPageLoad()))
Add logger please

2024-07-22 15:16 UTC, yasaracar commented on app/controllers/adjustment/AdjustmentRepackagedTaxTypeController.scala
> +                  case _                                    => Future.successful(Redirect(controllers.routes.JourneyRecoveryController.onPageLoad()))
Add logger please

2024-07-22 15:16 UTC, yasaracar commented on app/controllers/adjustment/AdjustmentSmallProducerReliefDutyRateController.scala
> +              case _                                                                            => Future.successful(Redirect(controllers.routes.JourneyRecoveryController.onPageLoad()))
Add logger please

2024-07-22 15:16 UTC, yasaracar commented on app/controllers/adjustment/AdjustmentVolumeController.scala
> +      case _                                                                                         => Future.successful(Redirect(controllers.routes.JourneyRecoveryController.onPageLoad()))
Add logger please

2024-07-22 15:16 UTC, yasaracar commented on app/controllers/adjustment/AdjustmentVolumeWithSPRController.scala
> +      case _                                                                                         => Future.successful(Redirect(controllers.routes.JourneyRecoveryController.onPageLoad()))
Add logger please

2024-07-22 15:16 UTC, yasaracar commented on app/controllers/adjustment/CheckYourAnswersController.scala
> +      result.getOrElse(Future.successful(Redirect(controllers.routes.JourneyRecoveryController.onPageLoad())))
Add logger please

2024-07-22 15:16 UTC, yasaracar commented on app/controllers/adjustment/CheckYourAnswersController.scala
> +      case None                 => Future.successful(Redirect(controllers.routes.JourneyRecoveryController.onPageLoad()))
Add logger please

2024-07-22 15:16 UTC, yasaracar commented on app/controllers/adjustment/WhenDidYouPayDutyController.scala
> +              case _                                                                            => Future.successful(Redirect(controllers.routes.JourneyRecoveryController.onPageLoad()))
Add logger please

2024-07-23 08:45 UTC, yasaracar requested changes

2024-07-23 08:45 UTC, yasaracar commented on app/controllers/adjustment/AdjustmentRepackagedTaxTypeController.scala
> +        logger.warn("Couldn't fetch correct AdjustmentEntry from user answers")
You use the same logger message in multiple places which will make it harder to identify the issue, can you use different error messages by being more descriptive around what really happened for that line. 
Applies to the whole PR

2024-07-23 08:45 UTC, yasaracar commented on app/controllers/adjustment/CheckYourAnswersController.scala
> +        logger.warn("Couldn't fetch correct AdjustmentEntry from user answers")
You use the same logger message in multiple places which will make it harder to identify the issue, can you use different error messages by being more descriptive around what really happened for that line.

2024-07-23 12:02 UTC, yasaracar approved these changes

2024-07-25 15:50 UTC, msatta submitted a review, later dismissed

2024-07-26 08:33 UTC, msatta approved these changes

2024-07-26 10:59 UTC, msatta approved these changes

2024-07-26 13:45 UTC, merged