ADR-1175 unit testing for pay link
hmrc/alcohol-duty-returns-frontend pull request #126
Opened 2024-08-08 09:17 UTC by JemmaEdwards

2024-08-08 13:42 UTC, davidfes submitted a review, later dismissed

2024-08-08 20:27 UTC, yasaracar requested changes

2024-08-08 20:27 UTC, yasaracar commented on test/connectors/PayApiConnectorSpec.scala
> +
Missing test case for:

 case Left(errorResponse: UpstreamErrorResponse)    =>

2024-08-09 16:09 UTC, davidfes approved these changes

2024-08-09 16:28 UTC, merged