ADR-1275 direct debit link
hmrc/alcohol-duty-returns-frontend pull request #127
Opened 2024-08-08 12:45 UTC by JemmaEdwards

2024-08-08 13:44 UTC, davidfes commented on test/controllers/StartDirectDebitControllerSpec.scala
> +  val startDirectDebitRequest =
unused

2024-08-08 13:47 UTC, davidfes submitted a review, later dismissed

2024-08-08 20:22 UTC, yasaracar requested changes

2024-08-08 20:22 UTC, yasaracar commented on test/models/payments/DirectDebitModelsSpec.scala
> +/*
There is no business logic in Direct Debits models so we don't need these tests

2024-08-08 20:22 UTC, yasaracar commented on test/connectors/DirectDebitConnectorSpec.scala
> +
Missing tests case for:
 case Left(errorResponse: UpstreamErrorResponse)    =>

2024-08-09 16:09 UTC, davidfes approved these changes

2024-08-09 16:46 UTC, merged