Adr 806
hmrc/alcohol-duty-returns-frontend pull request #17
Opened 2023-12-14 16:40 UTC by sini-george

2023-12-15 10:10 UTC, Ewan-James-Donovan approved these changes
Lgtm!

2023-12-15 14:47 UTC, yasaracar commented on app/views/DeclareSpiritsTotalView.scala.html
> +        @pageHeading(messages("declareSpiritsTotal.heading"))
You don't need to split pageHeading if there is no separate content like a paragrarh between the heading and the radio buttons.

2023-12-15 15:06 UTC, Ewan-James-Donovan requested changes

2023-12-15 15:06 UTC, Ewan-James-Donovan commented on app/views/DeclareSpiritsTotalView.scala.html
> +        @pageHeading(messages("declareSpiritsTotal.heading"))
True:

 @govukInput(
        InputViewModel(
            field = form("declare-spirits-total-input"),
            label = LabelViewModel(messages("declareSpiritsTotal.heading")).asPageHeading(),

            ....

2023-12-15 15:33 UTC, Ewan-James-Donovan approved these changes
LGTM

2023-12-18 17:21 UTC, yasaracar approved these changes

2023-12-18 17:22 UTC, merged