ADR-829: Declare Scotch Whisky page changes
hmrc/alcohol-duty-returns-frontend pull request #19
Opened 2023-12-18 10:09 UTC by sini-george

Scotch Whisky page changes

2023-12-18 10:53 UTC, yasaracar requested changes

2023-12-18 10:53 UTC, yasaracar commented on app/views/DeclareScotchWhiskyView.scala.html
> +            field = form("declare-scotch-whisky-input"),
Can you align this with one more tab please?

2023-12-18 12:14 UTC, sini-george commented on app/views/DeclareScotchWhiskyView.scala.html
> +            field = form("declare-scotch-whisky-input"),
Done

2023-12-18 12:33 UTC, yasaracar submitted a review, later dismissed

2023-12-19 12:14 UTC, yasaracar approved these changes

2023-12-19 12:15 UTC, merged