ADR-830 - Irish Whisky screen
hmrc/alcohol-duty-returns-frontend pull request #20
Opened 2023-12-18 16:25 UTC by TPilkington94Dev

Irish Whisky screen created and validations implemented. All tests ran and passed.

2023-12-18 17:16 UTC, yasaracar approved these changes

2023-12-20 09:34 UTC, sini-george submitted a review, later dismissed

2023-12-21 10:49 UTC, yasaracar requested changes

2023-12-21 10:49 UTC, yasaracar commented on conf/messages.en
> +declareIrishWhiskey.inputSuffix = litres
The page doesn't seem to use this anymore, can you remove it please?

2023-12-21 10:49 UTC, yasaracar commented on app/views/DeclareIrishWhiskeyView.scala.html
> +       ButtonViewModel("saveAndContinueButton", messages("site.saveAndContinue"))
Fix the indentation please

2023-12-21 11:03 UTC, yasaracar submitted a review, later dismissed

2023-12-22 15:32 UTC, closed without merging