ADR-1535 Select appropriate regime where possible in dynamic content
hmrc/alcohol-duty-returns-frontend pull request #235
Opened 2024-12-05 18:50 UTC by davidfes

2024-12-10 11:04 UTC, ajchilts submitted a review, later dismissed

2024-12-10 12:57 UTC, yasaracar requested changes

2024-12-10 12:57 UTC, yasaracar commented on app/viewmodels/declareDuty/RateBandHelper.scala
> +    val rangeDetails =
This is repeated below, can we create a function like abvRangesFromRateBand?

2024-12-10 18:08 UTC, davidfes commented on app/viewmodels/declareDuty/RateBandHelper.scala
> +    val rangeDetails =
Done, makes sense.

2024-12-11 11:57 UTC, yasaracar approved these changes

2024-12-12 14:43 UTC, merged