ADR-1030 Add OtherMaltedGrains spirits page
hmrc/alcohol-duty-returns-frontend pull request #78
Opened 2024-04-25 08:17 UTC by davidfes

Draft - couple of error messages still outstanding

2024-04-25 08:56 UTC, sini-george commented on conf/messages.en
> +otherMaltedGrains.error.otherMaltedGrainsTypes.length = TBD must be 120 characters or less
The length ones can be taken out as they are not used

2024-04-25 15:42 UTC, davidfes commented on conf/messages.en
> +otherMaltedGrains.error.otherMaltedGrainsTypes.length = TBD must be 120 characters or less
Fixed

2024-04-26 09:43 UTC, yasaracar requested changes

2024-04-26 09:43 UTC, yasaracar commented on app/views/spiritsQuestions/OtherMaltedGrainsView.scala.html
> +                label = LabelViewModel(messages("otherMaltedGrains.subheading1")).asVisuallyHidden()
Testers raised an issue with the subheadings. Sinimol did a fix on a parallel branch where she uses the label instead but with some extra css. Can you use the same fix here please? 
[ADR-988 Pull Request](https://github.com/hmrc/alcohol-duty-returns-frontend/pull/77/files#diff-405601217f4e953299b66ced2b67313a2168a99b5055710c682f37ee5a718a6bR51)

2024-04-26 09:43 UTC, yasaracar commented on app/views/spiritsQuestions/OtherMaltedGrainsView.scala.html
> +                label = LabelViewModel(messages("otherMaltedGrains.subheading2")).asVisuallyHidden()
same as above

2024-04-26 12:49 UTC, davidfes commented on app/views/spiritsQuestions/OtherMaltedGrainsView.scala.html
> +                label = LabelViewModel(messages("otherMaltedGrains.subheading2")).asVisuallyHidden()
fixed here too

2024-04-26 14:40 UTC, yasaracar approved these changes

2024-04-30 08:42 UTC, yasaracar approved these changes

2024-04-30 11:04 UTC, merged