ADR-999 Add Other Spirits Produced page
hmrc/alcohol-duty-returns-frontend pull request #80
Opened 2024-04-25 15:49 UTC by davidfes

2024-04-26 09:54 UTC, yasaracar requested changes

2024-04-26 09:54 UTC, yasaracar commented on app/viewmodels/govuk/TextAreaFluency.scala
> +  object TextareaViewModel extends ErrorMessageAwareness {
Seems like we are using CharacterCountViewModel instead. Do we need to keep this?

2024-04-26 09:54 UTC, yasaracar commented on app/views/spiritsQuestions/OtherSpiritsProducedView.scala.html
> +                label = LabelViewModel(messages("otherSpiritsProduced.subheading1")).asVisuallyHidden()
We use the input element's label as heading when there is no element between the heading and the first input element. Please see https://github.com/hmrc/alcohol-duty-returns-frontend/blob/main/app/views/productEntry/AlcoholByVolumeQuestionView.scala.html#L49

2024-04-26 12:19 UTC, davidfes commented on app/viewmodels/govuk/TextAreaFluency.scala
> +  object TextareaViewModel extends ErrorMessageAwareness {
We can delete it, but I wondered if it would be useful to leave it anyway to save that work being done again. Don't mind either way.

2024-04-26 12:41 UTC, davidfes commented on app/views/spiritsQuestions/OtherSpiritsProducedView.scala.html
> +                label = LabelViewModel(messages("otherSpiritsProduced.subheading1")).asVisuallyHidden()
Fixed. Still waiting on a error message fix though before the ticket is done (moved back to blocked)

2024-04-30 09:14 UTC, davidfes commented on app/views/spiritsQuestions/OtherSpiritsProducedView.scala.html
> +                label = LabelViewModel(messages("otherSpiritsProduced.subheading1")).asVisuallyHidden()
Error messages updated.

2024-04-30 10:18 UTC, yasaracar submitted a review, later dismissed

2024-04-30 12:05 UTC, yasaracar approved these changes

2024-04-30 15:49 UTC, merged