ADR-786 Add authentication
hmrc/alcohol-duty-returns-frontend pull request #94
Opened 2024-05-28 20:08 UTC by davidfes

2024-05-28 20:08 UTC, davidfes commented
Previous PR here: https://github.com/hmrc/alcohol-duty-returns-frontend/pull/93

2024-05-29 15:43 UTC, davidfes commented on test/controllers/actions/IdentifierActionSpec.scala
> +        .thenReturn(Future(combine(combine(Some(internalId), Some(groupId)), enrolments)))
Couldn't work out why it wouldn't let me use ~ here so had to rename to combine. That said |+| and using cats Monoid would have been a better choice IMO but that's what it is.

2024-05-29 16:02 UTC, yasaracar requested changes

2024-05-29 16:02 UTC, yasaracar commented on test/controllers/actions/IdentifierActionSpec.scala
> +        .thenReturn(Future(combine(combine(Some(internalId), Some(groupId)), enrolments)))
Something I experienced before, it is very annoying. You can try one of these two approaches:

https://github.com/hmrc/ni-exemption-returns-frontend/blob/main/test/controllers/actions/auth/GGAuthActionSpec.scala#L198

https://github.com/hmrc/economic-crime-levy-returns-frontend/blob/main/test/uk/gov/hmrc/economiccrimelevyreturns/controllers/actions/AuthorisedActionSpec.scala#L53

2024-05-30 08:21 UTC, davidfes commented on app/controllers/actions/IdentifierAction.scala
>          Redirect(routes.UnauthorisedController.onPageLoad)
Line 73 should be removed indeed since it's caught in the handleAuthException. Any other types aren't recovered as in the original. Good spot.

2024-05-30 13:27 UTC, yasaracar approved these changes

2024-06-03 15:00 UTC, yasaracar approved these changes

2024-06-03 15:52 UTC, merged