ADR-1097 Add no AppaId page
hmrc/alcohol-duty-returns-frontend pull request #95
Opened 2024-05-29 15:59 UTC by davidfes

2024-05-29 16:01 UTC, davidfes commented on conf/application.conf
> +  appaIdRegister       = "http://localhost:16000/manage-alcohol-duty"
To be updated when the guidance is ready

2024-05-31 08:33 UTC, yasaracar requested changes

2024-05-31 08:33 UTC, yasaracar commented on app/controllers/actions/IndentifierWithoutEnrolment.scala
> +      val internalId: String = getOrElseFailWithUnauthorised(optInternalId, "Unable to retrieve internalId")
I think we should have kept this simple, we don't need IdentifierWithoutEnrolmentRequest for these pages. I can't foresee any resaon we'd use internalId and groupId apart from logging but happy if it stays as well.

2024-05-31 08:33 UTC, yasaracar commented on app/controllers/actions/IndentifierWithoutEnrolment.scala
> +      case _: NoActiveSession        =>
No active session is an AuthorisationException as well so I think it makes more sense that it is in handleAuthException

2024-05-31 08:33 UTC, yasaracar commented on test/controllers/actions/IndentifierWithoutEnrolmentActionSpec.scala
> +    "redirect to the authorised page if not be authorised" in {
should be unauthorised page

2024-05-31 08:33 UTC, yasaracar commented on test/controllers/actions/IndentifierWithoutEnrolmentActionSpec.scala
> +      ).foreach { exception =>
Add UnauthorizedException as well please

2024-05-31 10:49 UTC, davidfes commented on app/controllers/actions/IndentifierWithoutEnrolment.scala
> +      case _: NoActiveSession        =>
It's the same as the catch all, so yes.

2024-05-31 11:10 UTC, davidfes commented on app/controllers/actions/IndentifierWithoutEnrolment.scala
> +      val internalId: String = getOrElseFailWithUnauthorised(optInternalId, "Unable to retrieve internalId")
Given it's a small number of pages I don't mind either way. Your call.

2024-05-31 11:12 UTC, davidfes commented on test/controllers/actions/IndentifierWithoutEnrolmentActionSpec.scala
> +    "redirect to the authorised page if not be authorised" in {
Fixed, and 'if not be' sounds a bit pirate to me. Yay!

2024-05-31 11:13 UTC, davidfes commented on conf/messages.en
> +noAppaId.link.id = register-for-alcohol-duty
Also was broken as its use wasn't referring to messages.

2024-06-03 10:17 UTC, yasaracar approved these changes

2024-06-05 09:31 UTC, yasaracar approved these changes

2024-06-05 09:31 UTC, merged