ADR-971 Check regimes for relevant DSD pages and for tasklist completion
hmrc/alcohol-duty-returns-frontend pull request #98
Opened 2024-06-06 09:56 UTC by davidfes

2024-06-06 10:01 UTC, davidfes commented on app/controllers/TaskListController.scala
> -        Ok(view(AlcoholDutyTaskListHelper.getTaskList(request.userAnswers, validUntil, periodKey)))
Using an object makes unit test hard, so changed to an injectable service

2024-06-06 10:02 UTC, davidfes commented on app/controllers/dutySuspended/DutySuspendedDeliveriesGuidanceController.scala
> +  }
So we can jump to the first relevant page via the navigator

2024-06-06 10:05 UTC, davidfes commented on app/models/RatePeriod.scala
> -sealed trait AlcoholRegime
Moved to own class using enumeratum

2024-06-06 10:05 UTC, davidfes commented on app/models/TaskListStatus.scala
> +
Preferred to strings (although converted to such to access messages)

2024-06-06 10:06 UTC, davidfes commented on app/models/package.scala
Saves having to write long form out everywhere we can return an error in an Either.

2024-06-06 10:06 UTC, davidfes commented on app/models/package.scala
> +  type Result[T] = Either[Throwable, T]
Saves having to write out long form whenever we return an error via an Either

2024-06-06 10:07 UTC, davidfes commented on app/services/tasklist/TaskListService.scala
> +class TaskListService @Inject() (returnTaskListCreator: ReturnTaskListCreator) {
Using an injectable makes the unit testing easier.

2024-06-06 10:08 UTC, davidfes commented on app/viewmodels/tasklist/ReturnTaskListCreator.scala
> +    createTaskListSection: () => Either[Throwable, TaskListItem],
Use Result[T] here ?

2024-06-06 10:11 UTC, davidfes commented on test/controllers/actions/CheckRegimeActionSpec.scala
> +  Seq(
I'm not sure about the cache api, since get(page, json) returns a Try[JsObject] so you'd need to save the updated user answers at each stage to put in the next, hence I've used a foldLeft to act as a loop with state. Probably should look at it again, but since it only affects tests for now I've not made any change.

2024-06-06 12:44 UTC, yasaracar approved these changes

2024-06-06 17:17 UTC, yasaracar requested changes

2024-06-06 17:17 UTC, yasaracar commented on app/models/AlcoholRegimes.scala
> +  def nextRegime(current: Option[AlcoholRegime]): Option[AlcoholRegime] = current match {
This looks to me a specific logic for Duty Suspended pages so better move it to DeclareDutySuspendedDeliveriesNavigator

2024-06-06 17:17 UTC, yasaracar commented on app/models/TaskListStatus.scala
> +  case object Completed extends TaskListStatus
Instead of calling Lowercase everytime this is used, please add entryName here

2024-06-07 09:01 UTC, davidfes commented on app/models/AlcoholRegimes.scala
> +  def hasOtherFermentedProduct() = hasCider() || hasWine() || regimes.contains(OtherFermentedProduct)
Cider isn't add though which was one of the asks on the ticket to also go to OtherFermented. I agree if that was fixed, but is it safe to do so?

2024-06-21 08:23 UTC, closed without merging